name: CI

on:
  push:
    branches:
      - main
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]
    paths-ignore:
    - README.md
    - .git*

permissions:
  contents: read

jobs:
  build-extension-windows-x64:
    name: Build extension (Windows x64)
    runs-on: windows-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: recursive

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - uses: taiki-e/install-action@3a911424851a96b72dc168c8dd71fd98ed215d66 # v2.68.36
        with:
          tool: protoc

      - name: Init Cargo cache
        uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1

      - name: Build
        run: cargo build --release

      - name: Test
        run: cargo test --release

      - name: Move library
        run: move target/release/minerva.dll minerva_x64.dll

      - name: Upload artifact
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: extension-x64-windows
          path: minerva_x64.dll
          retention-days: 1

  build-extension-linux-x64:
    name: Build extension (Linux x64)
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: recursive

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - uses: taiki-e/install-action@3a911424851a96b72dc168c8dd71fd98ed215d66 # v2.68.36
        with:
          tool: protoc

      - name: Init Cargo cache
        uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1

      - name: Build
        run: cargo build --release

      - name: Test
        run: cargo test --release

      - name: Move library
        run: mv target/release/libminerva.so minerva_x64.so

      - name: Strip library
        run: strip --strip-unneeded --keep-file-symbols minerva_x64.so

      - name: Upload artifact
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: extension-x64-linux
          path: minerva_x64.so
          retention-days: 1

  build:
    name: Build addon
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs:
      - build-extension-windows-x64
      - build-extension-linux-x64

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: recursive

      - name: Download Windows x64
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: extension-x64-windows
          path: .

      - name: Download Linux x64
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: extension-x64-linux
          path: .

      - name: Install HEMTT
        uses: arma-actions/hemtt@main

      - name: Run HEMTT build
        run: hemtt release

      - name: Upload Artifact
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: addon
          path: releases/minerva-latest.zip
          if-no-files-found: error
