name: CI

on:
  push:
    branches:
      - main
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]
    paths-ignore:
    - README.md
    - .git*

permissions:
  contents: read

jobs:
  build-extension-windows-x64:
    name: Build extension (Windows x64)
    runs-on: windows-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          submodules: recursive

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - uses: taiki-e/install-action@b9c5db3aef04caffaf95a1d03931de10fb2a140f # v2.65.1
        with:
          tool: protoc

      - name: Init Cargo cache
        uses: Swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5 # v2.8.2

      - name: Build
        run: cargo build --release

      - name: Test
        run: cargo test --release

      - name: Move library
        run: move target/release/minerva.dll minerva_x64.dll

      - name: Upload artifact
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6
        with:
          name: extension-x64-windows
          path: minerva_x64.dll
          retention-days: 1

  build-extension-linux-x64:
    name: Build extension (Linux x64)
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          submodules: recursive

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - uses: taiki-e/install-action@b9c5db3aef04caffaf95a1d03931de10fb2a140f # v2.65.1
        with:
          tool: protoc

      - name: Init Cargo cache
        uses: Swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5 # v2.8.2

      - name: Build
        run: cargo build --release

      - name: Test
        run: cargo test --release

      - name: Move library
        run: mv target/release/libminerva.so minerva_x64.so

      - name: Strip library
        run: strip --strip-unneeded --keep-file-symbols minerva_x64.so

      - name: Upload artifact
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6
        with:
          name: extension-x64-linux
          path: minerva_x64.so
          retention-days: 1

  build:
    name: Build addon
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs:
      - build-extension-windows-x64
      - build-extension-linux-x64

    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          submodules: recursive

      - name: Download Windows x64
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7
        with:
          name: extension-x64-windows
          path: .

      - name: Download Linux x64
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7
        with:
          name: extension-x64-linux
          path: .

      - name: Install HEMTT
        uses: arma-actions/hemtt@main

      - name: Run HEMTT build
        run: hemtt release

      - name: Upload Artifact
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6
        with:
          name: addon
          path: releases/minerva-latest.zip
          if-no-files-found: error
