name: Format

on:
  workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  rustfmt:
    name: Check
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install Rust
        uses: dtolnay/rust-toolchain@6bed0761d98439e5a578e2877258200ad565ba87 # stable
        with:
          components: rustfmt

      - name: Check formatting
        run: cargo fmt --all -- --check
